let countryList = {
  AUD: { code: "AU", name: "Australian Dollar" },
  BGN: { code: "BG", name: "Bulgarian Lev" },
  BRL: { code: "BR", name: "Brazilian Real" },
  CAD: { code: "CA", name: "Canadian Dollar" },
  CHF: { code: "CH", name: "Swiss Franc" },
  CNY: { code: "CN", name: "Chinese Yuan" },
  CZK: { code: "CZ", name: "Czech Koruna" },
  DKK: { code: "DK", name: "Danish Krone" },
  EUR: { code: "EU", name: "Euro" },
  GBP: { code: "GB", name: "British Pound" },
  HKD: { code: "HK", name: "Hong Kong Dollar" },
  HUF: { code: "HU", name: "Hungarian Forint" },
  IDR: { code: "ID", name: "Indonesian Rupiah" },
  ILS: { code: "IL", name: "Israeli Shekel" },
  INR: { code: "IN", name: "Indian Rupee" },
  ISK: { code: "IS", name: "Icelandic Króna" },
  JPY: { code: "JP", name: "Japanese Yen" },
  KRW: { code: "KR", name: "South Korean Won" },
  MXN: { code: "MX", name: "Mexican Peso" },
  MYR: { code: "MY", name: "Malaysian Ringgit" },
  NOK: { code: "NO", name: "Norwegian Krone" },
  NZD: { code: "NZ", name: "New Zealand Dollar" },
  PHP: { code: "PH", name: "Philippine Peso" },
  PLN: { code: "PL", name: "Polish Złoty" },
  RON: { code: "RO", name: "Romanian Leu" },
  SEK: { code: "SE", name: "Swedish Krona" },
  SGD: { code: "SG", name: "Singapore Dollar" },
  THB: { code: "TH", name: "Thai Baht" },
  TRY: { code: "TR", name: "Turkish Lira" },
  USD: { code: "US", name: "United States Dollar" },
  ZAR: { code: "ZA", name: "South African Rand" },
};
